Update 01-code.Rmd
juancarloscastillo/multivariada pull request #5
Opened 2020-04-20 21:58 UTC by jciturras

labels cortas para variables

2020-04-21 02:00 UTC, juancarloscastillo commented on content/assignment/01-code.Rmd
>  Para el procesamiento de cada variables se seguirá el siguiente flujo de trabajo:
cada variable

2020-04-21 02:02 UTC, juancarloscastillo requested changes
realizar cambios

2020-04-21 02:02 UTC, juancarloscastillo commented on content/assignment/01-code.Rmd
> +proc_elsoc$mesfuerzo <- set_label(x = proc_elsoc$mesfuerzo,label = "Recompenda: esfuerzo")
recompenda?

2020-04-21 02:02 UTC, juancarloscastillo commented on content/assignment/01-code.Rmd
> +proc_elsoc$mtalento  <- set_label(x = proc_elsoc$mtalento, label = "Recompenda: talento")
recompenda

2020-04-21 02:02 UTC, juancarloscastillo commented on content/assignment/01-code.Rmd
> +proc_elsoc$edcine <- set_label(x = proc_elsoc$edcine,label = "Educacion")
Educación

2020-04-21 14:29 UTC, jciturras commented
cambios realizados

2020-04-22 00:50 UTC, juancarloscastillo approved these changes

2020-04-22 00:51 UTC, merged